/**
 * What common shell commands accept, for autocomplete: subcommands, options
 * and whether arguments are paths. Deliberately small and hand-written — the
 * goal is the everyday server-admin vocabulary, with a one-line hint each.
 */
export interface Spec {
  /** One-line description. */
  d: string;
  sub?: Record<string, Spec>;
  /** [option, description] */
  opts?: [string, string][];
  /** Arguments are files/directories ("dirs": directories only). */
  paths?: boolean | "dirs";
}

const s = (d: string, rest: Omit<Spec, "d"> = {}): Spec => ({ d, ...rest });
const p = (d: string, opts?: [string, string][]): Spec => ({ d, paths: true, opts });

const SYSTEMCTL_UNIT = (d: string) => s(d);

const DOCKER_SUB: Record<string, Spec> = {
  ps: s("List containers", { opts: [["-a", "All containers, also stopped"], ["-q", "Only IDs"], ["--format", "Format output"]] }),
  images: s("List images", { opts: [["-a", "All images"], ["-q", "Only IDs"]] }),
  run: s("Run a new container", {
    opts: [
      ["-d", "Detached (background)"],
      ["-it", "Interactive with a terminal"],
      ["--rm", "Remove when it exits"],
      ["-p", "Publish port host:container"],
      ["-v", "Mount volume host:container"],
      ["-e", "Set environment variable"],
      ["--name", "Container name"],
      ["--restart", "Restart policy (unless-stopped, always)"],
      ["--network", "Connect to a network"],
    ],
  }),
  exec: s("Run a command in a running container", { opts: [["-it", "Interactive with a terminal"], ["-u", "User"], ["-w", "Working directory"]] }),
  logs: s("Show container logs", { opts: [["-f", "Follow"], ["--tail", "Number of lines"], ["--since", "Since time, e.g. 10m"], ["-t", "Timestamps"]] }),
  start: s("Start stopped containers"),
  stop: s("Stop running containers"),
  restart: s("Restart containers"),
  rm: s("Remove containers", { opts: [["-f", "Force (stop first)"], ["-v", "Also remove volumes"]] }),
  rmi: s("Remove images", { opts: [["-f", "Force"]] }),
  pull: s("Download an image"),
  push: s("Upload an image"),
  build: s("Build an image from a Dockerfile", { paths: "dirs", opts: [["-t", "Name:tag"], ["-f", "Dockerfile path"], ["--no-cache", "Don't use cache"]] }),
  inspect: s("Low-level details as JSON", { opts: [["-f", "Format with a Go template"]] }),
  stats: s("Live resource usage", { opts: [["--no-stream", "Print once"]] }),
  top: s("Processes of a container"),
  cp: s("Copy files between container and host", { paths: true }),
  network: s("Manage networks", { sub: { ls: s("List networks"), create: s("Create a network"), rm: s("Remove networks"), inspect: s("Show details"), prune: s("Remove unused networks") } }),
  volume: s("Manage volumes", { sub: { ls: s("List volumes"), create: s("Create a volume"), rm: s("Remove volumes"), inspect: s("Show details"), prune: s("Remove unused volumes") } }),
  system: s("Manage Docker", { sub: { df: s("Disk usage"), prune: s("Remove unused data", { opts: [["-a", "Also unused images"], ["--volumes", "Also volumes"], ["-f", "Don't ask"]] }), info: s("System-wide information") } }),
  compose: s("Docker Compose", {
    sub: {
      up: s("Create and start services", { opts: [["-d", "Detached"], ["--build", "Build images first"], ["--force-recreate", "Recreate containers"], ["--remove-orphans", "Remove unknown containers"]] }),
      down: s("Stop and remove services", { opts: [["-v", "Also remove volumes"], ["--rmi", "Remove images (all, local)"]] }),
      ps: s("List services"),
      logs: s("Service logs", { opts: [["-f", "Follow"], ["--tail", "Number of lines"]] }),
      restart: s("Restart services"),
      stop: s("Stop services"),
      start: s("Start services"),
      pull: s("Pull service images"),
      build: s("Build services", { opts: [["--no-cache", "Don't use cache"]] }),
      exec: s("Run a command in a service"),
      config: s("Validate and show the config"),
    },
    opts: [["-f", "Compose file"], ["-p", "Project name"]],
  }),
  login: s("Log in to a registry"),
  tag: s("Tag an image"),
  prune: s("Remove unused data"),
};

const GIT_SUB: Record<string, Spec> = {
  status: s("Working tree status", { opts: [["-s", "Short format"], ["-b", "Show branch"]] }),
  add: p("Stage changes", [["-A", "All changes"], ["-p", "Pick hunks interactively"], [".", "Everything here"]]),
  commit: s("Record staged changes", { opts: [["-m", "Message"], ["-a", "Stage tracked changes first"], ["--amend", "Rewrite the last commit"]] }),
  push: s("Upload commits", { opts: [["-u", "Set upstream"], ["--force-with-lease", "Safe force push"], ["--tags", "Push tags"]] }),
  pull: s("Fetch and integrate", { opts: [["--rebase", "Rebase instead of merge"], ["--ff-only", "Only fast-forward"]] }),
  fetch: s("Download refs", { opts: [["--all", "All remotes"], ["--prune", "Drop deleted branches"]] }),
  clone: s("Copy a repository", { opts: [["--depth", "Shallow clone"], ["-b", "Branch"]] }),
  checkout: s("Switch branches or restore files", { paths: true, opts: [["-b", "Create a branch"], ["--", "Restore files"]] }),
  switch: s("Switch branches", { opts: [["-c", "Create a branch"]] }),
  branch: s("List or manage branches", { opts: [["-a", "Include remote"], ["-d", "Delete"], ["-D", "Force delete"], ["-m", "Rename"]] }),
  merge: s("Join histories", { opts: [["--no-ff", "Always create a merge commit"], ["--abort", "Abort the merge"]] }),
  rebase: s("Reapply commits on top of another base", { opts: [["-i", "Interactive"], ["--continue", "Continue"], ["--abort", "Abort"]] }),
  log: s("Show history", { opts: [["--oneline", "One line per commit"], ["--graph", "Draw the graph"], ["-n", "Limit count"], ["-p", "Show patches"], ["--stat", "Changed files"]] }),
  diff: p("Show changes", [["--staged", "Staged changes"], ["--stat", "Summary"], ["--name-only", "Only file names"]]),
  stash: s("Shelve changes", { sub: { push: s("Save changes"), pop: s("Apply and drop"), list: s("List stashes"), apply: s("Apply"), drop: s("Drop") } }),
  reset: s("Reset HEAD", { opts: [["--hard", "Discard changes"], ["--soft", "Keep changes staged"], ["HEAD~1", "One commit back"]] }),
  restore: p("Restore files", [["--staged", "Unstage"]]),
  remote: s("Manage remotes", { opts: [["-v", "Show URLs"]], sub: { add: s("Add a remote"), remove: s("Remove a remote"), "set-url": s("Change URL") } }),
  tag: s("Manage tags", { opts: [["-a", "Annotated"], ["-d", "Delete"]] }),
  show: s("Show an object"),
  rm: p("Remove files", [["--cached", "Only from the index"], ["-r", "Recursive"]]),
  mv: p("Move or rename"),
  "cherry-pick": s("Apply a commit"),
  revert: s("Revert a commit"),
  blame: p("Who changed each line"),
  config: s("Settings", { opts: [["--global", "For this user"], ["--list", "Show all"]] }),
  init: s("Create a repository"),
  clean: s("Remove untracked files", { opts: [["-n", "Dry run"], ["-fd", "Files and directories"]] }),
};

const SYSTEMCTL_SUB: Record<string, Spec> = {
  status: SYSTEMCTL_UNIT("Show service status"),
  start: SYSTEMCTL_UNIT("Start a service"),
  stop: SYSTEMCTL_UNIT("Stop a service"),
  restart: SYSTEMCTL_UNIT("Restart a service"),
  reload: SYSTEMCTL_UNIT("Reload configuration"),
  enable: s("Start at boot", { opts: [["--now", "And start now"]] }),
  disable: s("Don't start at boot", { opts: [["--now", "And stop now"]] }),
  "is-active": SYSTEMCTL_UNIT("Is it running?"),
  "is-enabled": SYSTEMCTL_UNIT("Does it start at boot?"),
  "list-units": s("Loaded units", { opts: [["--type=service", "Only services"], ["--state=running", "Only running"], ["--failed", "Only failed"]] }),
  "list-unit-files": s("Installed units"),
  "daemon-reload": s("Reload unit files"),
  cat: SYSTEMCTL_UNIT("Show the unit file"),
  edit: SYSTEMCTL_UNIT("Edit / override a unit"),
  mask: SYSTEMCTL_UNIT("Prevent starting"),
  unmask: SYSTEMCTL_UNIT("Allow starting again"),
  reboot: s("Reboot the machine"),
  poweroff: s("Power off the machine"),
};

const KUBECTL_SUB: Record<string, Spec> = {
  get: s("List resources", {
    sub: { pods: s("Pods"), svc: s("Services"), deploy: s("Deployments"), nodes: s("Nodes"), ns: s("Namespaces"), ingress: s("Ingresses"), all: s("Common resources") },
    opts: [["-n", "Namespace"], ["-A", "All namespaces"], ["-o", "Output (wide, yaml, json)"], ["-w", "Watch"], ["-l", "Label selector"]],
  }),
  describe: s("Show details", { opts: [["-n", "Namespace"]] }),
  logs: s("Pod logs", { opts: [["-f", "Follow"], ["--tail", "Number of lines"], ["-c", "Container"], ["-n", "Namespace"], ["--previous", "Previous instance"]] }),
  exec: s("Run in a pod", { opts: [["-it", "Interactive"], ["-n", "Namespace"], ["-c", "Container"]] }),
  apply: s("Apply a config", { paths: true, opts: [["-f", "File or directory"], ["-k", "Kustomize directory"]] }),
  delete: s("Delete resources", { opts: [["-f", "From file"], ["-n", "Namespace"]] }),
  rollout: s("Manage rollouts", { sub: { status: s("Rollout status"), restart: s("Restart"), undo: s("Roll back"), history: s("History") } }),
  scale: s("Set replicas", { opts: [["--replicas", "Count"]] }),
  "port-forward": s("Forward local ports"),
  top: s("Resource usage", { sub: { pods: s("Pods"), nodes: s("Nodes") } }),
  config: s("Kubeconfig", { sub: { "get-contexts": s("List contexts"), "use-context": s("Switch context"), "current-context": s("Show context") } }),
  edit: s("Edit a resource"),
  create: s("Create a resource"),
};

const APT_SUB: Record<string, Spec> = {
  update: s("Refresh package lists"),
  upgrade: s("Upgrade packages", { opts: [["-y", "Don't ask"]] }),
  "full-upgrade": s("Upgrade, also removing packages", { opts: [["-y", "Don't ask"]] }),
  install: s("Install packages", { opts: [["-y", "Don't ask"], ["--no-install-recommends", "Only required deps"]] }),
  remove: s("Remove packages", { opts: [["-y", "Don't ask"], ["--purge", "Also config files"]] }),
  purge: s("Remove with config files"),
  autoremove: s("Remove unneeded packages", { opts: [["-y", "Don't ask"]] }),
  search: s("Search packages"),
  show: s("Package details"),
  list: s("List packages", { opts: [["--installed", "Installed ones"], ["--upgradable", "Upgradable ones"]] }),
  policy: s("Installed and candidate versions"),
  clean: s("Clear the download cache"),
};

const NPM_SUB: Record<string, Spec> = {
  install: s("Install dependencies", { opts: [["-D", "As dev dependency"], ["-g", "Globally"], ["--save-exact", "Exact version"]] }),
  ci: s("Clean install from the lockfile"),
  run: s("Run a package script"),
  start: s("Run the start script"),
  test: s("Run tests"),
  build: s("Run the build script"),
  uninstall: s("Remove a package"),
  update: s("Update packages"),
  outdated: s("Show outdated packages"),
  ls: s("Installed packages", { opts: [["--depth=0", "Top level only"]] }),
  audit: s("Security audit", { sub: { fix: s("Fix vulnerabilities") } }),
  init: s("Create package.json", { opts: [["-y", "Defaults"]] }),
  publish: s("Publish the package"),
};

export const SPECS: Record<string, Spec> = {
  // Files & directories
  ls: p("List directory contents", [["-l", "Long format"], ["-a", "Include hidden"], ["-la", "Long, with hidden"], ["-lh", "Long, human sizes"], ["-t", "Sort by time"], ["-S", "Sort by size"], ["-R", "Recursive"]]),
  cd: { d: "Change directory", paths: "dirs" },
  pwd: s("Print working directory"),
  cat: p("Print files", [["-n", "Number lines"]]),
  less: p("View files page by page", [["+F", "Follow like tail -f"], ["-S", "Don't wrap lines"]]),
  more: p("View files page by page"),
  head: p("First lines of files", [["-n", "Number of lines"]]),
  tail: p("Last lines of files", [["-f", "Follow"], ["-F", "Follow, survive rotation"], ["-n", "Number of lines"]]),
  cp: p("Copy files", [["-r", "Recursive"], ["-a", "Archive (keep attributes)"], ["-i", "Ask before overwrite"], ["-v", "Verbose"]]),
  mv: p("Move or rename", [["-i", "Ask before overwrite"], ["-n", "Never overwrite"], ["-v", "Verbose"]]),
  rm: p("Remove files", [["-r", "Recursive"], ["-f", "Force"], ["-i", "Ask for each"], ["-v", "Verbose"]]),
  mkdir: { d: "Create directories", paths: "dirs", opts: [["-p", "With parents, no error if exists"]] },
  rmdir: { d: "Remove empty directories", paths: "dirs" },
  touch: p("Create files / update times"),
  ln: p("Create links", [["-s", "Symbolic link"], ["-f", "Replace existing"]]),
  chmod: p("Change permissions", [["-R", "Recursive"], ["+x", "Make executable"], ["755", "rwxr-xr-x"], ["644", "rw-r--r--"], ["600", "rw-------"]]),
  chown: p("Change owner", [["-R", "Recursive"]]),
  find: p("Search for files", [["-name", "By name"], ["-iname", "By name, any case"], ["-type", "f file, d directory"], ["-mtime", "Modified days ago"], ["-size", "By size, e.g. +100M"], ["-delete", "Delete matches"], ["-exec", "Run a command"]]),
  grep: p("Search text", [["-r", "Recursive"], ["-i", "Ignore case"], ["-n", "Line numbers"], ["-v", "Invert match"], ["-l", "Only file names"], ["-E", "Extended regex"], ["-c", "Count"], ["--color=auto", "Highlight"]]),
  du: p("Disk usage of files", [["-sh", "Summary, human sizes"], ["-h", "Human sizes"], ["--max-depth=1", "One level"]]),
  df: s("Free disk space", { opts: [["-h", "Human sizes"], ["-i", "Inodes"], ["-T", "Filesystem type"]] }),
  tar: p("Archive files", [["-czvf", "Create .tar.gz"], ["-xzvf", "Extract .tar.gz"], ["-xvf", "Extract"], ["-tvf", "List contents"], ["-C", "Change to directory"]]),
  zip: p("Create zip archives", [["-r", "Recursive"]]),
  unzip: p("Extract zip archives", [["-d", "Target directory"], ["-l", "List contents"]]),
  gzip: p("Compress files", [["-d", "Decompress"], ["-k", "Keep original"]]),
  stat: p("File details"),
  file: p("Detect file type"),
  wc: p("Count lines, words, bytes", [["-l", "Lines"]]),
  sort: p("Sort lines", [["-n", "Numeric"], ["-r", "Reverse"], ["-u", "Unique"], ["-h", "Human sizes"]]),
  uniq: p("Filter repeated lines", [["-c", "Count"]]),
  diff: p("Compare files", [["-u", "Unified format"], ["-r", "Recursive"]]),
  tree: { d: "Directory tree", paths: "dirs", opts: [["-L", "Depth"], ["-a", "Include hidden"]] },
  rsync: p("Sync files (local or remote)", [["-avz", "Archive, verbose, compress"], ["--delete", "Delete extra files"], ["--progress", "Show progress"], ["-n", "Dry run"], ["-e", "Remote shell, e.g. ssh -p 2222"]]),
  scp: p("Copy over SSH", [["-r", "Recursive"], ["-P", "Port"]]),
  // Editors & viewers
  vim: p("Edit files in Vim"),
  vi: p("Edit files in Vi"),
  nano: p("Edit files in nano"),
  // Processes & system
  ps: s("Processes", { opts: [["aux", "All processes"], ["-ef", "All, full format"], ["--sort=-%cpu", "By CPU"], ["--sort=-%mem", "By memory"]] }),
  top: s("Live processes"),
  htop: s("Interactive process viewer"),
  kill: s("Signal a process", { opts: [["-9", "Force kill (SIGKILL)"], ["-15", "Terminate (SIGTERM)"], ["-HUP", "Reload (SIGHUP)"]] }),
  pkill: s("Signal processes by name", { opts: [["-f", "Match full command line"], ["-9", "Force kill"]] }),
  killall: s("Kill processes by name"),
  pgrep: s("Find processes by name", { opts: [["-a", "Show command line"], ["-f", "Match full command line"]] }),
  free: s("Memory usage", { opts: [["-h", "Human sizes"], ["-m", "In MB"]] }),
  uptime: s("Uptime and load"),
  uname: s("System information", { opts: [["-a", "Everything"], ["-r", "Kernel release"]] }),
  whoami: s("Current user"),
  who: s("Logged-in users"),
  w: s("Who is logged in and what they do"),
  id: s("User and group IDs"),
  hostname: s("Show or set host name", { opts: [["-I", "IP addresses"]] }),
  hostnamectl: s("Host name and OS info"),
  timedatectl: s("Time and timezone"),
  date: s("Date and time"),
  lsblk: s("Block devices", { opts: [["-f", "With filesystems"]] }),
  lscpu: s("CPU information"),
  dmesg: s("Kernel messages", { opts: [["-T", "Readable timestamps"], ["-w", "Follow"], ["--level=err,warn", "Errors and warnings"]] }),
  journalctl: s("Systemd logs", { opts: [["-u", "Unit (service)"], ["-f", "Follow"], ["-n", "Number of lines"], ["--since", "Since, e.g. '1 hour ago'"], ["-p", "Priority, e.g. err"], ["-b", "This boot"], ["-xe", "Recent, with explanations"], ["--disk-usage", "Log size"], ["--vacuum-size=", "Shrink logs to size"]] }),
  systemctl: s("Control systemd services", { sub: SYSTEMCTL_SUB }),
  service: s("Control services (SysV)"),
  crontab: s("Scheduled jobs", { opts: [["-l", "List"], ["-e", "Edit"], ["-r", "Remove all"]] }),
  sudo: s("Run as another user (root)", { opts: [["-i", "Root login shell"], ["-u", "As user"], ["-s", "Shell"]] }),
  su: s("Switch user", { opts: [["-", "Login shell"]] }),
  passwd: s("Change password"),
  useradd: s("Create a user", { opts: [["-m", "Create home"], ["-s", "Shell"], ["-G", "Groups"]] }),
  usermod: s("Modify a user", { opts: [["-aG", "Add to groups"], ["-s", "Shell"], ["-L", "Lock"]] }),
  userdel: s("Delete a user", { opts: [["-r", "Also home directory"]] }),
  history: s("Command history", { opts: [["-c", "Clear"]] }),
  export: s("Set environment variable"),
  env: s("Environment variables"),
  echo: s("Print text"),
  source: p("Run a script in this shell"),
  which: s("Locate a command"),
  man: s("Manual pages"),
  watch: s("Run a command repeatedly", { opts: [["-n", "Interval (seconds)"], ["-d", "Highlight changes"]] }),
  screen: s("Terminal multiplexer", { opts: [["-S", "New named session"], ["-r", "Reattach"], ["-ls", "List sessions"]] }),
  tmux: s("Terminal multiplexer", { sub: { new: s("New session", { opts: [["-s", "Name"]] }), attach: s("Attach", { opts: [["-t", "Session"]] }), ls: s("List sessions"), "kill-session": s("Kill a session", { opts: [["-t", "Session"]] }) } }),
  reboot: s("Reboot"),
  shutdown: s("Power off or reboot", { opts: [["-h", "Halt"], ["-r", "Reboot"], ["now", "Immediately"], ["+10", "In 10 minutes"], ["-c", "Cancel"]] }),
  exit: s("Close the shell"),
  clear: s("Clear the screen"),
  // Network
  ping: s("Check reachability", { opts: [["-c", "Count"], ["-i", "Interval"]] }),
  curl: s("Transfer URLs", { opts: [["-I", "Headers only"], ["-L", "Follow redirects"], ["-o", "Save to file"], ["-O", "Save with remote name"], ["-s", "Silent"], ["-v", "Verbose"], ["-X", "Method"], ["-H", "Header"], ["-d", "Request body"], ["-k", "Ignore TLS errors"]] }),
  wget: s("Download files", { opts: [["-O", "Output file"], ["-c", "Continue"], ["-q", "Quiet"]] }),
  ssh: s("Connect over SSH", { opts: [["-p", "Port"], ["-i", "Identity file"], ["-L", "Local forward"], ["-D", "SOCKS proxy"], ["-J", "Jump host"], ["-v", "Verbose"]] }),
  "ssh-keygen": s("Create SSH keys", { opts: [["-t ed25519", "Ed25519 key"], ["-C", "Comment"], ["-f", "Output file"], ["-R", "Remove a host from known_hosts"]] }),
  "ssh-copy-id": s("Install your key on a server", { opts: [["-i", "Identity file"], ["-p", "Port"]] }),
  ip: s("Network configuration", { sub: { a: s("Addresses"), addr: s("Addresses"), r: s("Routes"), route: s("Routes"), link: s("Interfaces"), neigh: s("ARP table") } }),
  ss: s("Sockets", { opts: [["-tulpn", "Listening TCP/UDP with processes"], ["-s", "Summary"], ["-tn", "TCP connections"]] }),
  netstat: s("Network statistics", { opts: [["-tulpn", "Listening ports with processes"], ["-rn", "Routing table"]] }),
  dig: s("DNS lookup", { opts: [["+short", "Short answer"], ["MX", "Mail records"], ["TXT", "Text records"], ["@1.1.1.1", "Ask this resolver"]] }),
  nslookup: s("DNS lookup"),
  host: s("DNS lookup"),
  traceroute: s("Trace the network path"),
  mtr: s("Traceroute with stats", { opts: [["-r", "Report mode"]] }),
  nc: s("Netcat", { opts: [["-zv", "Check if a port is open"], ["-l", "Listen"]] }),
  ufw: s("Firewall", { sub: { status: s("Rules", { opts: [["verbose", "Details"], ["numbered", "With numbers"]] }), allow: s("Allow a port/service"), deny: s("Deny a port/service"), delete: s("Delete a rule"), enable: s("Turn on"), disable: s("Turn off"), reload: s("Reload") } }),
  iptables: s("Packet filter rules", { opts: [["-L", "List"], ["-n", "Numeric"], ["-v", "Verbose"], ["-A", "Append rule"], ["-D", "Delete rule"]] }),
  "firewall-cmd": s("firewalld", { opts: [["--list-all", "Show zone"], ["--add-port=", "Open a port"], ["--permanent", "Persist"], ["--reload", "Reload"]] }),
  certbot: s("Let's Encrypt certificates", { sub: { certonly: s("Get a certificate"), renew: s("Renew", { opts: [["--dry-run", "Test only"]] }), certificates: s("List certificates") }, opts: [["--nginx", "Use the nginx plugin"], ["-d", "Domain"]] }),
  nginx: s("Web server", { opts: [["-t", "Test configuration"], ["-s reload", "Reload"], ["-T", "Show full config"]] }),
  // Packages & runtimes
  apt: s("Debian/Ubuntu packages", { sub: APT_SUB }),
  "apt-get": s("Debian/Ubuntu packages", { sub: APT_SUB }),
  dnf: s("Fedora/RHEL packages", { sub: { install: s("Install"), remove: s("Remove"), update: s("Update"), search: s("Search"), info: s("Details"), list: s("List") } }),
  yum: s("RHEL/CentOS packages", { sub: { install: s("Install"), remove: s("Remove"), update: s("Update"), search: s("Search"), info: s("Details"), list: s("List") } }),
  apk: s("Alpine packages", { sub: { add: s("Install"), del: s("Remove"), update: s("Refresh index"), upgrade: s("Upgrade"), search: s("Search") } }),
  snap: s("Snap packages", { sub: { install: s("Install"), remove: s("Remove"), list: s("List"), refresh: s("Update") } }),
  docker: s("Containers", { sub: DOCKER_SUB }),
  "docker-compose": s("Docker Compose (v1)", { sub: DOCKER_SUB.compose.sub, opts: DOCKER_SUB.compose.opts }),
  kubectl: s("Kubernetes", { sub: KUBECTL_SUB }),
  git: s("Version control", { sub: GIT_SUB }),
  npm: s("Node packages", { sub: NPM_SUB }),
  yarn: s("Node packages", { sub: { add: s("Add a dependency"), install: s("Install"), remove: s("Remove"), build: s("Build"), dev: s("Dev server"), start: s("Start") } }),
  pnpm: s("Node packages", { sub: { add: s("Add"), install: s("Install"), remove: s("Remove"), run: s("Run a script") } }),
  node: p("Run JavaScript"),
  python3: p("Run Python", [["-m", "Run a module"], ["-c", "Run code"], ["-V", "Version"]]),
  python: p("Run Python", [["-m", "Run a module"], ["-c", "Run code"]]),
  pip: s("Python packages", { sub: { install: s("Install", { opts: [["-r", "From requirements file"], ["-U", "Upgrade"], ["--user", "For this user"]] }), uninstall: s("Remove"), list: s("List"), freeze: s("Pinned list"), show: s("Details") } }),
  pip3: s("Python packages", { sub: { install: s("Install", { opts: [["-r", "From requirements file"], ["-U", "Upgrade"]] }), uninstall: s("Remove"), list: s("List"), freeze: s("Pinned list") } }),
  make: s("Run Makefile targets", { opts: [["-j", "Parallel jobs"], ["-C", "In directory"]] }),
  pm2: s("Node process manager", { sub: { list: s("Processes"), logs: s("Logs"), restart: s("Restart"), stop: s("Stop"), start: s("Start"), delete: s("Remove"), monit: s("Monitor"), save: s("Save process list") } }),
  // Databases
  mysql: s("MySQL client", { opts: [["-u", "User"], ["-p", "Ask password"], ["-h", "Host"], ["-e", "Execute"]] }),
  mysqldump: s("Dump MySQL databases", { opts: [["-u", "User"], ["-p", "Ask password"], ["--all-databases", "Everything"], ["--single-transaction", "Consistent InnoDB dump"]] }),
  psql: s("PostgreSQL client", { opts: [["-U", "User"], ["-h", "Host"], ["-d", "Database"], ["-c", "Run command"], ["-l", "List databases"]] }),
  pg_dump: s("Dump a PostgreSQL database", { opts: [["-U", "User"], ["-F c", "Custom format"], ["-f", "Output file"]] }),
  "redis-cli": s("Redis client", { opts: [["-h", "Host"], ["-p", "Port"], ["-a", "Password"], ["ping", "Check the server"], ["info", "Server info"]] }),
};

/** Command names for the first word, alphabetically. */
export const COMMAND_NAMES = Object.keys(SPECS).sort();
